apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: flux
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
        version: "1.12.1"
    spec:
      containers: 
        - name: nginx
          image: nginx:1.12.1
          ports:
            - name: http
              containerPort: 80
