apiVersion: v1
kind: Service
metadata: 
  name: nginx
  namespace: flux
  labels: 
    name: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    name: nginx
    version: "1.12"
  type: LoadBalancer
